// Generated by CoffeeScript 1.12.4
var Core, colors, fs, homeDir, path, program;

colors = require('colors');

path = require('path');

program = require('commander');

fs = require('fs');

global.VERSION = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8')).version;

global.DEBUG = process.env.DEBUG || false;

global.PLATFORM = process.platform;

Core = require('plethora-atlas-core');

homeDir = Core.getHomeDir();

global.homeDir = homeDir;

global.modulesDir = path.join(__dirname, 'node_modules/');

global.modules = [];

global.config = require(homeDir + "/config");

global.config.keys = require(homeDir + "/keys");

global.Helpers = Core.Helpers;

Core.createPackagesDir();

module.exports = function() {
  console.log("PlethoraThemes".cyan + (" Atlas CLI v" + global.VERSION).magenta + (" [os:" + PLATFORM + "]").gray + (" [debug:" + global.DEBUG + "]").gray);
  Core.loadModules(program);
  return Core.init(program);
};
